In [1]:
import numpy as np
import networkx as nx
import traci
import sumolib
import random

In [2]:

net = sumolib.net.readNet("data/rand_grid_small/rand_grid_small.net.xml")

Sumo_config = [
    'sumo',
    '-c', "data/rand_grid_small/rand_grid_small.sumocfg",
    '--step-length', '1',
    '--start'
]
traci.start(Sumo_config)
edges = net.getEdges()

 Retrying in 1 seconds

In [3]:
time_elapsed = 0
current_timestep = 0
travel_times = []
while time_elapsed < 15000:
    veh_id = f"ugv_{time_elapsed}"
    randomedge = random.choice(edges)._id
    traci.person.add(veh_id, randomedge, 0)
    traci.person.appendWalkingStage(veh_id, [randomedge], 
                                    arrivalPos=-1, speed=5.0)
    traci.simulationStep()
    time_elapsed = traci.simulation.getTime()
    start_time = time_elapsed
    while veh_id in traci.person.getIDList():
        traci.simulationStep()
        time_elapsed = traci.simulation.getTime()
    travel_times.append(time_elapsed - start_time)

Step #13400.00 (1ms ~= 1000.00*RT, ~13000.00UPS, TraCI: 0ms, vehicles TOT 2681 ACT 13 BUF tep #4500.00 (0ms ?*RT. ?UPS, TraCI: 1ms, vehicles TOT 901 ACT 12 BUF 0)                 ep #9000.00 (0ms ?*RT. ?UPS, TraCI: 1ms, vehicles TOT 1801 ACT 14 BUF 0)

In [4]:
traci.close()

Step #15020.00 (0ms ?*RT. ?UPS, TraCI: 1370ms, vehicles TOT 3004 ACT 16 BUF 0)

In [5]:
travel_times = np.array(travel_times)
print(f"Average travel time: {np.mean(travel_times)} s")

Average travel time: 37.9119170984456 s

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("runs/dijkstra/simulation_results1.csv")
df

,start_idx,target_idx,warm_up_time,tour_start_time,total_time_taken,path_length
0,0,1,1000,1005,75,4
1,0,10,1000,1005,27,2
2,0,14,1000,1005,33,2
3,0,4,1000,1005,87,6
4,0,2,1000,1005,105,5
...,...,...,...,...,...,...
2315,79,30,1000,1005,18,3
2316,79,36,1000,1005,87,5
2317,79,44,1000,1005,213,11
2318,79,59,1000,1005,42,1
2319,79,78,1000,1005,51,3

In [10]:
df[['total_time_taken', 'path_length']].describe()

       total_time_taken  path_length
count       2320.000000  2320.000000
mean         128.375431     6.129741
std           76.993467     3.342201
min            6.000000     1.000000
25%           66.000000     4.000000
50%          123.000000     6.000000
75%          183.000000     8.000000
max          372.000000    17.000000